import BioShockLogo from './assets/BioShockLogo.jpg';
import gta5Logo from './assets/gta5Logo.png';
import TLoULogo from './assets/TLoULogo.png';
import bf4Logo from './assets/bf4Logo.png';
import crysisLogo from './assets/crysisLogo.jpg';
import assassinLogo from './assets/assassinLogo.jpg';
import deadSpaceLogo from './assets/deadSpaceLogo.jpg';
import metroLogo from './assets/metroLogo.jpg';
import saintsRowLogo from './assets/saintsRowLogo.jpg';
import tombRaiderLogo from './assets/tombRaiderLogo.jpeg';
import AssassinCreedFon from './assets/AssassinCreedFon.jpg';
import BattlefieldFon from './assets/BattlefieldFon.jpg';
import BioShockFon from './assets/bioshockFon.jpg';
import CrysisFon from './assets/CrysisFon.jpg';
import DeadSpaceFon from './assets/DeadSpaceFon.jpg';
import GTA5Fon from './assets/gta5fon.jpeg';
import MetroFon from './assets/MetroFon.jpg';
import SaintsRowFon from './assets/SaintsRowFon.jpeg';
import TLoUFon from './assets/TLoU1Fon.jpg';
import TombRaiderFon from './assets/TombRaiderFon.jpeg';

const games = [
    {
        id: 1,
        title: 'BioShock Infinite',
        genre: 'Экшен',
        description: 'BioShock Infinite - это шутер от первого лица с элементами ролевой игры, действие которого разворачивается в 1912 году в парящем городе Колумбия.',
        platforms: 'Windows, PlayStation 3, Xbox 360',
        rating: 95,
        logo: BioShockLogo,
        background: BioShockFon,
        releaseDate: '26 марта 2013',
        publisher: '2K Games',
        localization: 'Русский, Английский, Французский, Немецкий, Испанский, Итальянский, Польский, Чешский',
        keywords: 'шутер, ролевые элементы, стелс, альтернативная история',
        sales: '11 миллионов копий',
        price: '$59.99',
        screenshots: [BioShockFon, BioShockFon, BioShockFon, BioShockFon, BioShockFon],
    },
    {
        id: 2,
        title: 'The Last of Us',
        genre: 'Экшен-приключение',
        description: 'The Last of Us - это постапокалиптическая игра, сосредоточенная на выживании и эмоциональной истории Джоэла и Элли.',
        platforms: 'PlayStation 3',
        rating: 95,
        logo: TLoULogo,
        background: TLoUFon,
        releaseDate: '14 июня 2013',
        publisher: 'Sony Computer Entertainment',
        localization: 'Русский, Английский, Французский, Немецкий, Испанский, Итальянский, Португальский',
        keywords: 'выживание, постапокалипсис, стелс, эмоциональная драма',
        sales: '17 миллионов копий',
        price: '$59.99',
        screenshots: [TLoUFon, TLoUFon, TLoUFon, TLoUFon, TLoUFon],
    },
    {
        id: 3,
        title: 'Grand Theft Auto V',
        genre: 'Открытый мир',
        description: 'Grand Theft Auto V предлагает огромный открытый мир и три переплетающихся истории главных героев.',
        platforms: 'PlayStation 3, Xbox 360',
        rating: 97,
        logo: gta5Logo,
        background: GTA5Fon,
        releaseDate: '17 сентября 2013',
        publisher: 'Rockstar Games',
        localization: 'Русский, Английский, Французский, Немецкий, Испанский, Итальянский, Японский, Китайский',
        keywords: 'открытый мир, криминал, экшен, мультиплеер',
        sales: '185 миллионов копий',
        price: '$59.99',
        screenshots: [GTA5Fon, GTA5Fon, GTA5Fon, GTA5Fon, GTA5Fon],
    },
    {
        id: 4,
        title: 'Assassin`s Creed IV - Black Flag',
        genre: 'Экшен-приключение',
        description: 'Assassin`s Creed IV: Black Flag - это приключенческий боевик, действие которого разворачивается в Карибском море во времена Золотого века пиратства, в начале XVIII века.',
        platforms: 'Windows, PlayStation 3, Xbox 360',
        rating: 81,
        logo: assassinLogo,
        background: AssassinCreedFon,
        releaseDate: '29 октября 2013',
        publisher: 'Ubisoft',
        localization: 'Русский, Английский, Французский, Немецкий, Испанский, Итальянский, Португальский',
        keywords: 'пираты, открытый мир, стелс, морские сражения',
        sales: '11 миллионов копий',
        price: '$59.99',
        screenshots: [AssassinCreedFon, AssassinCreedFon, AssassinCreedFon, AssassinCreedFon, AssassinCreedFon],
    },
    {
        id: 5,
        title: 'Battlefield 4',
        genre: 'Шутер',
        description: 'Battlefield 4 предлагает масштабные сражения с техникой и пехотой в реалистичных условиях.',
        platforms: 'Windows, PlayStation 3, Xbox 360',
        rating: 88,
        logo: bf4Logo,
        background: BattlefieldFon,
        releaseDate: '29 октября 2013',
        publisher: 'Electronic Arts',
        localization: 'Русский, Английский, Французский, Немецкий, Испанский, Итальянский',
        keywords: 'шутер, многопользовательская игра, военные сражения, техника',
        sales: '15 миллионов копий',
        price: '$59.99',
        screenshots: [BattlefieldFon, BattlefieldFon, BattlefieldFon, BattlefieldFon, BattlefieldFon],
    },
    {
        id: 6,
        title: 'Crysis 3',
        genre: 'Шутер',
        description: 'Crysis 3 - это футуристический шутер с акцентом на использование высокотехнологичного костюма.',
        platforms: 'Windows, Xbox 360',
        rating: 91,
        logo: crysisLogo,
        background: CrysisFon,
        releaseDate: '19 февраля 2013',
        publisher: 'Electronic Arts',
        localization: 'Русский, Английский, Французский, Немецкий, Испанский, Итальянский',
        keywords: 'шутер, наука-фантастика, нано-костюм, экшен',
        sales: '5 миллионов копий',
        price: '$59.99',
        screenshots: [CrysisFon, CrysisFon, CrysisFon, CrysisFon, CrysisFon],
    },
    {
        id: 7,
        title: 'Dead Space',
        genre: 'Хоррор',
        description: 'Dead Space - это survival horror игра, действие которой происходит на космическом корабле.',
        platforms: 'Windows, PlayStation 3, Xbox 360',
        rating: 89,
        logo: deadSpaceLogo,
        background: DeadSpaceFon,
        releaseDate: '13 октября 2008',
        publisher: 'Electronic Arts',
        localization: 'Русский, Английский, Французский, Немецкий, Испанский, Итальянский',
        keywords: 'хоррор, космос, выживание, экшен',
        sales: '3.2 миллиона копий',
        price: '$19.99',
        screenshots: [DeadSpaceFon, DeadSpaceFon, DeadSpaceFon, DeadSpaceFon, DeadSpaceFon],
    },
    {
        id: 8,
        title: 'Metro: Last Light',
        genre: 'Шутер',
        description: 'Metro: Last Light - это постапокалиптический шутер с элементами хоррора, основанный на романе Глуховского.',
        platforms: 'Windows, Xbox 360',
        rating: 82,
        logo: metroLogo,
        background: MetroFon,
        releaseDate: '14 мая 2013',
        publisher: 'Deep Silver',
        localization: 'Русский, Английский, Французский, Немецкий, Испанский, Польский',
        keywords: 'шутер, постапокалипсис, хоррор, выживание',
        sales: '4.5 миллиона копий',
        price: '$49.99',
        screenshots: [MetroFon, MetroFon, MetroFon, MetroFon, MetroFon],
    },
    {
        id: 9,
        title: 'Saints Row',
        genre: 'Открытый мир',
        description: 'Saints Row - это безумная игра с открытым миром, полная юмора и хаоса.',
        platforms: 'Windows, PlayStation 3, Xbox 360',
        rating: 85,
        logo: saintsRowLogo,
        background: SaintsRowFon,
        releaseDate: '15 августа 2013',
        publisher: 'Deep Silver',
        localization: 'Русский, Английский, Французский, Немецкий, Испанский, Итальянский',
        keywords: 'открытый мир, юмор, экшен, кастомизация',
        sales: '6 миллионов копий',
        price: '$49.99',
        screenshots: [SaintsRowFon, SaintsRowFon, SaintsRowFon, SaintsRowFon, SaintsRowFon],
    },
    {
        id: 10,
        title: 'Tomb Raider',
        genre: 'Экшен-приключение',
        description: 'Tomb Raider - это перезапуск серии, где Лара Крофт проходит испытания на выживание.',
        platforms: 'Windows, PlayStation 3, Xbox 360',
        rating: 87,
        logo: tombRaiderLogo,
        background: TombRaiderFon,
        releaseDate: '5 марта 2013',
        publisher: 'Square Enix',
        localization: 'Русский, Английский, Французский, Немецкий, Испанский, Итальянский',
        keywords: 'приключения, выживание, экшен, археология',
        sales: '14.5 миллионов копий',
        price: '$59.99',
        screenshots: [TombRaiderFon, TombRaiderFon, TombRaiderFon, TombRaiderFon, TombRaiderFon],
    },
];

export default games;
